In [ ]:
#creating ndarray
import numpy as np 
num = np.array([5,10,15,20,25])
print(num)

[ 5 10 15 20 25]


In [ ]:
#printings its type
print(type(num))

<class 'numpy.ndarray'>


In [4]:
#creating an array and multypling with 50
x = np.array([100,200,300])
print(x+50)

[150 250 350]


In [5]:
#creating a ndarray and mutliply it by 5
y = np.array([2,4,6,8])
print(y*5)

[10 20 30 40]


In [ ]:
#mini challange by chatgpt to increase the evary item price by 20 rupees
prices = np.array([120,250,310,150])
print(prices+20)

[140 270 330 170]


In [7]:
arr = np.zeros(8)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
arr = np.ones(10, dtype = int)
print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [13]:
arr = np.arange(5,55,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [14]:
arr = np.linspace(0,30,7)
print(arr)

[ 0.  5. 10. 15. 20. 25. 30.]
