In [ ]:
#numpy -> Numerical Python is a library used for

# -> Fast numerical computation
# -> Mathematical operations
# -> Handling large datasets
# -> Scientific computing

# * The main object inside NumPy is the ndarray.

# * Think of it as a supercharged list.

In [1]:
import numpy as np

print(np.__version__)

2.2.6


In [7]:
#creating an array
import numpy as np

arr = np.array([10,20,30,40])

print(arr)

[10 20 30 40]


In [9]:
# diff between lit and numpy
nums = [1,2,3,4,5,6]
numss = np.array([1,2,3,4,5,6])
print(nums, type(numss))
print(numss, type(numss))


[1, 2, 3, 4, 5, 6] <class 'numpy.ndarray'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [5]:
import numpy as np
nums = np.array([1,2,3,4,5,6])
print (nums + 2)

[3 4 5 6 7 8]
