In [ ]:
#creating ndarray
import numpy as np 
num = np.array([5,10,15,20,25])
print(num)

[ 5 10 15 20 25]


In [ ]:
#printings its type
print(type(num))

<class 'numpy.ndarray'>


In [4]:
#creating an array and multypling with 50
x = np.array([100,200,300])
print(x+50)

[150 250 350]


In [5]:
#creating a ndarray and mutliply it by 5
y = np.array([2,4,6,8])
print(y*5)

[10 20 30 40]


In [ ]:
#mini challange by chatgpt to increase the evary item price by 20 rupees
prices = np.array([120,250,310,150])
print(prices+20)

[140 270 330 170]


In [7]:
arr = np.zeros(8)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
arr = np.ones(10, dtype = int)
print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [13]:
arr = np.arange(5,55,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [16]:
arr = np.linspace(0,30,7, dtype= int)
print(arr)

[ 0  5 10 15 20 25 30]


In [22]:
arr = np.linspace(0,30,7).astype(int)
print(arr)

[ 0  5 10 15 20 25 30]


In [18]:
arr = np.random.randint(100,500,15)
print(arr)

[241 351 336 354 197 323 367 386 459 431 401 162 413 234 149]


In [19]:
#mini challange by chatgpt
# You're creating a dummy sales dataset for one month.

# Create an array of 30 random daily sales values between 500 and 5000.
# Print the array.
# Multiply every sale by 1.18 to simulate adding 18% GST.
# Print the updated array.


In [20]:
sales = np.random.randint(500,5000,30)
print(sales)
gst = sales * 1.18
print(gst)

[4451 1482 2414 2098 1717 1144 4181 3917 2652 4021 3961 3441 3400 3403
  985 3499 3968  578 3578 4755 3528 2249 3178 4389  539 2196 3393 4012
 2438 2704]
[5252.18 1748.76 2848.52 2475.64 2026.06 1349.92 4933.58 4622.06 3129.36
 4744.78 4673.98 4060.38 4012.   4015.54 1162.3  4128.82 4682.24  682.04
 4222.04 5610.9  4163.04 2653.82 3750.04 5179.02  636.02 2591.28 4003.74
 4734.16 2876.84 3190.72]
