In [ ]:
#numpy -> Numerical Python is a library used for

# -> Fast numerical computation
# -> Mathematical operations
# -> Handling large datasets
# -> Scientific computing

# * The main object inside NumPy is the ndarray.

# * Think of it as a supercharged list.

In [1]:
import numpy as np

print(np.__version__)

2.2.6


In [7]:
#creating an array
import numpy as np

arr = np.array([10,20,30,40])

print(arr)

[10 20 30 40]


In [9]:
# diff between lit and numpy
nums = [1,2,3,4,5,6]
numss = np.array([1,2,3,4,5,6])
print(nums, type(numss))
print(numss, type(numss))


[1, 2, 3, 4, 5, 6] <class 'numpy.ndarray'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [3]:
import numpy as np
nums = np.array([1,2,3,4,5,6])
print (nums + 2)

[3 4 5 6 7 8]


In [ ]:
print(nums.ndim)
print(nums.shape)
print(nums.size)
print(nums.itemsize) #items size 
print(nums.dtype)

1
(6,)
6
8
int64


In [40]:
nums = [[[1,2,3,4,5],[6,7,8,9,10]],[[6,7,8,9,10],[1,2,3,4,5]], [[6,7,8,9,10],[1,2,3,4,5]], [[6,7,8,9,10],[1,2,3,4,5]]]
print(nums)
nums_arr = np.array(nums)
print(nums_arr)
print(nums_arr.shape)
print(nums_arr.size)
print(nums_arr.dtype)
print(nums_arr.itemsize)

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[6, 7, 8, 9, 10], [1, 2, 3, 4, 5]], [[6, 7, 8, 9, 10], [1, 2, 3, 4, 5]], [[6, 7, 8, 9, 10], [1, 2, 3, 4, 5]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]]
(4, 2, 5)
40
int64
8


In [41]:
print(nums_arr)

print(nums_arr.shape)
print(nums_arr.size)
print(nums_arr.ndim)



[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]]
(4, 2, 5)
40
3


In [24]:
#arange is used to declare a range and get the elements in that range
arr = np.arange(1,16, dtype="int32")
arr = arr.reshape(3,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [27]:
arr = arr.reshape(15,1)
print(arr)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [29]:
arr = arr.reshape(5,3)
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [8]:
import datetime
nums = np.arange(1,100000001)


In [10]:
start = datetime.datetime.now()
print(sum(nums))
end = datetime.datetime.now()- start
print(end)

5000000050000000
0:00:02.594257


In [11]:
nums =[]
for i in range (1,100000001):
    nums.append(i)
start = datetime.datetime.now()
print(sum(nums))
end = datetime.datetime.now()- start
print(end)


5000000050000000
0:00:00.341139


In [14]:
import datetime
nums = np.arange(1,100000001)
start = datetime.datetime.now()
print(nums.sum())
end = datetime.datetime.now()- start
print(end)

5000000050000000
0:00:00.028419


In [ ]:
#mean
nums = np.arange(1,100000001)
print(nums.mean())

50000000.5


In [18]:
nums = np.random.randint(1,100,25)
print(nums)
print(nums.mean())

[91 29 86 95 88 18 76 56 98 61 66 43 35  3 25 94 37  6 52 96 32 44 20 69
  3]
52.92


In [ ]:
#min
nums = np.random.randint(30,77,5)
print(nums)
print(nums.min())

[55 66 37 30 67]
30


In [ ]:
#max
nums = np.random.randint(55,99,13)
print(nums)
print(nums.max())

[89 74 84 74 67 71 74 78 91 61 66 88 78]
91


In [ ]:
#standard deviation
marks = np.random.randint(70,100,15)
print(marks)
print(marks.std())
print(marks.mean())

[85 77 92 79 78 97 72 95 71 77 82 73 79 70 85]
8.247827996913289
80.8


In [ ]:
#variance
nums = np.random.randint(44,99,11)
print(nums)
print(nums.var())

[73 47 57 63 49 77 73 89 45 53 66]
181.17355371900828


In [ ]:
#argmax usedto find the position of maximum value in the array
nums = np.random.randint(22,44,9)
print(nums)
print(nums.argmax())

[24 39 42 36 25 23 25 42 43]
8


In [ ]:
#argmin used to find the position of minimum value in the array
nums = np.random.randint(22,44,9)
print(nums)
print(nums.argmin())

[24 22 28 31 27 42 41 31 34]
1


In [ ]:
#sqrt used to find the square root of the elements in the array
nums = np.random.randint(1,50,10)
print(nums)
print(np.sqrt(nums))

[13 42 17 12 18 20 45 10  1 30]
[3.60555128 6.4807407  4.12310563 3.46410162 4.24264069 4.47213595
 6.70820393 3.16227766 1.         5.47722558]


In [ ]:
#pow is used to find the poer of the elements in the array by giving the how much power we wanted from the elements 
nums = np.random.randint(1,50,10)
print(nums)
print(np.pow(nums,3))

[ 1 18 33 45 40  6 32 29 31 27]
[    1  5832 35937 91125 64000   216 32768 24389 29791 19683]


In [ ]:
#round function is used to round the float values in the array
nums = np.random.rand(1,4,10)
print(nums)
print(np.round(nums))

[[[0.83226851 0.6098829  0.68026864 0.97310554 0.80276454 0.72334769
   0.05148237 0.1901608  0.15909778 0.64221184]
  [0.06211051 0.71009377 0.38603138 0.97792062 0.21026119 0.3798625
   0.38099941 0.19948999 0.74448543 0.77461804]
  [0.14630476 0.66489585 0.96313206 0.48548081 0.05071015 0.68667509
   0.3618728  0.22365526 0.55833284 0.45031247]
  [0.14071705 0.32004734 0.64956151 0.42045707 0.24209302 0.37491652
   0.82624911 0.99647377 0.50942346 0.94912907]]]
[[[1. 1. 1. 1. 1. 1. 0. 0. 0. 1.]
  [0. 1. 0. 1. 0. 0. 0. 0. 1. 1.]
  [0. 1. 1. 0. 0. 1. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0. 0. 1. 1. 1. 1.]]]


In [ ]:
#abs is used to turn the negative values in the array to positive values
nums = np.array([-1,2,3,-4])
print(nums)
print(np.abs(nums))

[-1  2  3 -4]
[1 2 3 4]


In [ ]:
#sort is used to sort the values in the array into ascending order
nums = np.random.randint(1,50,10)
print(nums)
print(np.sort(nums))

[38  2 16 30 47 30 40 14 42 46]
[ 2 14 16 30 30 38 40 42 46 47]


In [ ]:
#sort is used to sort the values in the array into decending order
nums = np.random.randint(1,50,10)
print(nums)
sortt = np.sort(nums) [::-1]
print(sortt)

[ 4 38 15 21  8 32 17 48 13 33]
[48 38 33 32 21 17 15 13  8  4]


In [ ]:
#where is used to find the elements postion based on the condition we have given
nums = np.array([1,2,5,77,3,44,6,22])
print(np.where(nums > 30))

(array([3, 5]),)


In [ ]:
#unique is used to remove the repeated or dupilicate values 
nums = np.array([1,2,3,44,2,5,77,3,44,6,22])
print(np.unique(nums))

[ 1  2  3  5  6 22 44 77]
