In [1]:
import numpy as np

In [ ]:
#numpy zeroes()
# it creates a array filled with xeroes, by default it is stored in float value,
#but we can modify it by declaring the data type,
# it is useful in some cases example:- 

In [45]:
arr = np.zeros(5)
print(arr)


[0. 0. 0. 0. 0.]


In [52]:
arrs = np.zeros(5, dtype = int)
print(arrs)
print(arr.shape)


[0 0 0 0 0]
(5,)


In [53]:
arrs = np.zeros((5,5),dtype='int64')
print(arrs)
print(arr.shape)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(5,)


In [11]:
#numpy ones()
# it creates a array filled with ones, by default it is stored in float value,
#but we can modify it by declaring the data type,

In [12]:
arrs = np.ones((5,5), dtype=int)
print(arrs)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [13]:
#numpy identity()
# it creates a array filled with ones with the diagonal column, by default it is stored in float value,
#but we can modify it by declaring the data type,

In [16]:
arrs = np.identity((5),dtype= int)
print(arrs)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [18]:
arrs = np.eye((5), dtype=int)
print(arrs)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [20]:
#the diff bertween the identity and eye is eye can do regular matrixes also 

In [22]:
arrs = np.eye(3,5, dtype=int)
print(arrs)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [ ]:
#empty is used to declare thezeroes like the zeroes function but it is empty 

In [26]:
arr = np.empty((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
#full
arrs = np.full(3,5)
print(arrs)

[5 5 5]


In [29]:
#arange
# nums = ( start, stop, step)

In [30]:
nums = np.arange(1,10)
print(nums)

[1 2 3 4 5 6 7 8 9]


In [31]:
nums = np.arange(1,10,2)
print(nums)

[1 3 5 7 9]


In [33]:
nums = np.arange(10,0,-1)
print(nums)

[10  9  8  7  6  5  4  3  2  1]


In [34]:
#linspace
# nums = (start, stop , number of values)

In [36]:
arr = np.linspace(1,10,5, dtype=int)
print(arr)

[ 1  3  5  7 10]


In [37]:
# the difference bwtween the arange and the linsapce is that 
#arange controls the step size and the #linspace will comtrol how many values have to return, 
# like homany parts we want to make the range of nums

In [44]:
#random
#nums = (start, stop, how many random numbers to generate)
#uses rand for decimal values
# uses randint for onteger values

In [41]:
nums = np.random.randint(1,100,5)
print(nums)

[93 39 40 21 56]


In [43]:
nums = np.random.rand(1,10,5)
print(nums)

[[[0.92549964 0.802471   0.87392185 0.22781202 0.23733376]
  [0.4410238  0.14053026 0.90311867 0.80006431 0.63143531]
  [0.19406268 0.04878144 0.99007683 0.0460773  0.02574799]
  [0.37577953 0.96444666 0.11657757 0.16381389 0.76797864]
  [0.6617982  0.71559244 0.56453488 0.08737089 0.14862014]
  [0.23789929 0.6402521  0.183858   0.92455143 0.66084368]
  [0.39855844 0.78085294 0.35816929 0.34162974 0.2724046 ]
  [0.96400107 0.61447751 0.75612819 0.02402858 0.02117981]
  [0.76414536 0.6545104  0.40188012 0.25478869 0.72360761]
  [0.11695874 0.65763256 0.16818559 0.61794672 0.98255026]]]
