In [ ]:
#numpy -> Numerical Python is a library used for

# -> Fast numerical computation
# -> Mathematical operations
# -> Handling large datasets
# -> Scientific computing

# * The main object inside NumPy is the ndarray.

# * Think of it as a supercharged list.

In [1]:
import numpy as np

print(np.__version__)

2.2.6


In [7]:
#creating an array
import numpy as np

arr = np.array([10,20,30,40])

print(arr)

[10 20 30 40]


In [9]:
# diff between lit and numpy
nums = [1,2,3,4,5,6]
numss = np.array([1,2,3,4,5,6])
print(nums, type(numss))
print(numss, type(numss))


[1, 2, 3, 4, 5, 6] <class 'numpy.ndarray'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [3]:
import numpy as np
nums = np.array([1,2,3,4,5,6])
print (nums + 2)

[3 4 5 6 7 8]


In [ ]:
print(nums.ndim)
print(nums.shape)
print(nums.size)
print(nums.itemsize) #items size 
print(nums.dtype)

1
(6,)
6
8
int64


In [15]:
nums = [[[1,2,3,4,5],[6,7,8,9,10]],[[6,7,8,9,10],[1,2,3,4,5]]]
print(nums)
nums_arr = np.array(nums)
print(nums_arr)
print(nums_arr.shape)
print(nums_arr.size)
print(nums_arr.dtype)
print(nums_arr.itemsize)

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[6, 7, 8, 9, 10], [1, 2, 3, 4, 5]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]]
(2, 2, 5)
20
int64
8


In [24]:
#arange is used to declare a range and get the elements in that range
arr = np.arange(1,16, dtype="int32")
arr = arr.reshape(3,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [27]:
arr = arr.reshape(15,1)
print(arr)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [29]:
arr = arr.reshape(5,3)
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
